services:
  app:
    build:
      context: .
      dockerfile: docker/errata.Dockerfile
      target: app-dev
    init: true
    command: sleep infinity
    depends_on:
      - db
    ipc: host
    environment:
      DISPLAY: host.docker.internal:0
    user: notroot
    volumes:
      - .:/workspace
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    build:
      context: .
      dockerfile: docker/db.Dockerfile
    restart: unless-stopped
    volumes:
      - errata_data:/var/lib/postgresql/data

  celery:
    image: "${COMPOSE_PROJECT_NAME}-app"
    command: [ "/celery-init.sh" ]  # without beat
#    command: [ "/celery-init.sh", "-BE" ]  # with beat
    depends_on:
      - db
      - mq
    volumes:
      - .:/workspace
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mq:
    image: rabbitmq:4.2-management

  mailpit:
    image: axllent/mailpit:v1.27
    environment:
      - MP_DISABLE_VERSION_CHECK=true
      - MP_LABEL=ErrataMail
    ports:
      - "8825:8025"


volumes:
  errata_data:
