services:
  app:
    build:
      context: .
      dockerfile: docker/errata.Dockerfile
      target: app-dev
    init: true
    command: sleep infinity
    depends_on:
      - db
    ipc: host
    environment:
      DISPLAY: host.docker.internal:0
    user: notroot
    volumes:
      - .:/workspace
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    build:
      context: .
      dockerfile: docker/db.Dockerfile
    restart: unless-stopped
    volumes:
      - errata_data:/var/lib/postgresql/data

  celery:
    image: "${COMPOSE_PROJECT_NAME}-app"
    command:
      - "/celery-init.sh"
    depends_on:
      - db
      - mq
    volumes:
      - .:/workspace
    extra_hosts:
      - "host.docker.internal:host-gateway"
  mq:
    image: rabbitmq:4.2-management

volumes:
  errata_data:
