services:
  app:
    build:
      context: .
      dockerfile: docker/errata.Dockerfile
#      target: app-dev
    init: true
    command: sleep infinity
    depends_on:
      - db
    ipc: host
    environment:
      DISPLAY: host.docker.internal:0
    user: notroot

  db:
    build:
      context: .
      dockerfile: docker/db.Dockerfile
    restart: unless-stopped
    volumes:
      - errata_data:/var/lib/postgresql/data

volumes:
  errata_data:
